const constants = {
    REQUEST_RECIPES: 'REQUEST_RECIPES',
    RECEIVE_RECIPES: 'RECEIVE_RECIPES',
    OPEN_ADD_RECIPE_FORM: 'OPEN_ADD_RECIPE_FORM',
    CLOSE_ADD_RECIPE_FORM: 'CLOSE_ADD_RECIPE_FORM',
    CREATE_RECIPE: 'CREATE_RECIPE',
    POSTING_RECIPE: 'POSTING_RECIPE',
    SAVE_RECIPE: 'SAVE_RECIPE'
};

export default constants;